databases:
  - name: deploy
    databaseName: deploy
    user: deploy

services:
  - type: web
    name: deploy
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn deploy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: deploy
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
